version: '3'

services:
  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 80:80
    command: [ 'npm', 'start' ]

  browserless:
    image: browserless/chrome
    ports:
      - 3000:3000
